version: '3.8'

services:
  maddy:
    image: foxcpp/maddy:latest
    container_name: maddy-mail
    hostname: mail.${DOMAIN:-localhost}
    restart: unless-stopped
    ports:
      # SMTP
      - "25:25"     # SMTP (receive mail)
      - "587:587"   # SMTP (submission)
      - "465:465"   # SMTPS (submission over TLS)
      # IMAP
      - "143:143"   # IMAP
      - "993:993"   # IMAPS
      # HTTP (metrics, optional)
      - "8085:8080" # Metrics endpoint
    volumes:
      - ./data:/data
      - ./config/maddy.conf:/etc/maddy/maddy.conf
      - ./certs:/certs
    environment:
      - MADDY_DOMAIN=${DOMAIN:-localhost}
      - MADDY_HOSTNAME=mail.${DOMAIN:-localhost}
    networks:
      - homelab

  # Webmail interface using Roundcube
  webmail:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    ports:
      - "8086:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=maddy
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=maddy
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    volumes:
      - ./roundcube/config:/var/roundcube/config
      - ./roundcube/db:/var/roundcube/db
      - ./roundcube/temp:/tmp/roundcube-temp
    depends_on:
      - maddy
    networks:
      - homelab

networks:
  homelab:
    external: true
