version: '3.8'

services:
  # Simple all-in-one mail server
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.acebuddy.quest
    restart: unless-stopped
    ports:
      - "25:25"    # SMTP
      - "143:143"  # IMAP
      - "465:465"  # SMTPS
      - "587:587"  # Submission
      - "993:993"  # IMAPS
    volumes:
      - ./mail-data/data:/var/mail
      - ./mail-data/state:/var/mail-state
      - ./mail-data/logs:/var/log/mail
      - ./mail-data/config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_LDAP=0
      - ENABLE_QUOTAS=1
      - ENABLE_UPDATE_CHECK=1
      - PERMIT_DOCKER=network
      - SSL_TYPE=self-signed
      - SPOOF_PROTECTION=0
      - POSTFIX_MESSAGE_SIZE_LIMIT=100000000
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_INET_PROTOCOLS=ipv4
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - homelab

  # Roundcube webmail (already running, kept for reference)
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube-mail
    restart: unless-stopped
    ports:
      - "8086:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,newmail_notifier,managesieve,password
    volumes:
      - ./roundcube/config:/var/roundcube/config
      - ./roundcube/db:/var/roundcube/db
      - ./roundcube/temp:/tmp/roundcube-temp
    depends_on:
      - mailserver
    networks:
      - homelab

  # Alternative: Poste.io (simpler all-in-one)
  # Uncomment to use instead of mailserver above
  # poste:
  #   image: analogic/poste.io
  #   container_name: poste
  #   hostname: mail.acebuddy.quest
  #   restart: unless-stopped
  #   ports:
  #     - "25:25"
  #     - "80:80"
  #     - "443:443"
  #     - "110:110"
  #     - "143:143"
  #     - "465:465"
  #     - "587:587"
  #     - "993:993"
  #     - "995:995"
  #   volumes:
  #     - ./poste-data:/data
  #   environment:
  #     - DISABLE_CLAMAV=true
  #     - DISABLE_SPAMASSASSIN=false
  #     - DISABLE_RSPAMD=false
  #     - HOSTNAME=mail.acebuddy.quest
  #   networks:
  #     - homelab

networks:
  homelab:
    external: true
