version: "3.8"

services:
  # ==========================================
  # AI & Dashboard Services
  # ==========================================

  web-ui:
    image: nginx:alpine
    container_name: web-ui
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web-ui/index.html:/usr/share/nginx/html/index.html:ro
      - ./web-ui/dashboard.html:/usr/share/nginx/html/dashboard.html:ro
      - ./web-ui/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ollama
      - app-backend
    networks:
      - homelab

  app-backend:
    build: ./web-ui
    container_name: app-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./web-ui/app.js:/app/app.js:ro
    depends_on:
      - ollama
    networks:
      - homelab

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=5m
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G
    networks:
      - homelab

  # ==========================================
  # Email Services
  # ==========================================

  maddy:
    image: foxcpp/maddy:latest
    container_name: maddy-mail
    hostname: mail.localhost
    restart: unless-stopped
    ports:
      - "2525:25" # SMTP (receive - using alt port to avoid conflict)
      - "587:587" # SMTP (submission)
      - "465:465" # SMTPS
      - "143:143" # IMAP
      - "993:993" # IMAPS
    volumes:
      - ./email/data:/data
      - ./email/config/maddy.conf:/etc/maddy/maddy.conf
    environment:
      - MADDY_DOMAIN=localhost
      - MADDY_HOSTNAME=mail.localhost
    networks:
      - homelab

  webmail:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    ports:
      - "8086:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=maddy
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=maddy
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    volumes:
      - ./email/roundcube/config:/var/roundcube/config
      - ./email/roundcube/db:/var/roundcube/db
      - ./email/roundcube/temp:/tmp/roundcube-temp
    depends_on:
      - maddy
    networks:
      - homelab

  # ==========================================
  # Calendar Services
  # ==========================================

  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    restart: unless-stopped
    ports:
      - "5232:5232"
    volumes:
      - ./calendar/data:/data
      - ./calendar/config:/config:ro
    environment:
      - RADICALE_STORAGE_FILESYSTEM_FOLDER=/data/collections
      - RADICALE_AUTH_TYPE=htpasswd
      - RADICALE_AUTH_HTPASSWD_FILENAME=/config/users
      - RADICALE_AUTH_HTPASSWD_ENCRYPTION=bcrypt
      - RADICALE_RIGHTS_TYPE=owner_only
      - RADICALE_WEB_TYPE=internal
    networks:
      - homelab
    user: "1000:1000"

  # ==========================================
  # Cloud Storage (Nextcloud)
  # ==========================================

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - nextcloud_data:/var/www/html
      - ./nextcloud/apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-changeme}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-changeme}
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud
      - OVERWRITEPROTOCOL=http
      - OVERWRITEHOST=localhost:8082
    depends_on:
      - nextcloud-db
    networks:
      - homelab

  nextcloud-db:
    image: postgres:15-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-changeme}
    networks:
      - homelab

  # ==========================================
  # Matrix Chat (Optional - can be enabled)
  # ==========================================

  # matrix-synapse:
  #   image: matrixdotorg/synapse:latest
  #   container_name: matrix-synapse
  #   restart: unless-stopped
  #   ports:
  #     - "8008:8008"
  #     - "8448:8448"
  #   volumes:
  #     - ./matrix/data:/data
  #     - ./matrix/homeserver.yaml:/data/homeserver.yaml
  #   environment:
  #     - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
  #   networks:
  #     - homelab

  # ==========================================
  # Reverse Proxy (Caddy)
  # ==========================================

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - homelab

  # ==========================================
  # API Gateway
  # ==========================================

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVICES_CONFIG=/app/services.json
    volumes:
      - ./api-gateway/services.json:/app/services.json:ro
    depends_on:
      - web-ui
      - ollama
    networks:
      - homelab

# ==========================================
# Volumes
# ==========================================

volumes:
  ollama_data:
    driver: local
  nextcloud_data:
    driver: local
  nextcloud_db:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

# ==========================================
# Networks
# ==========================================

networks:
  homelab:
    external: true
