services:
  matrix-postgres:
    image: postgres:15-alpine
    container_name: matrix-postgres
    restart: unless-stopped
    env_file: ../.env
    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: ${MATRIX_DB_PASSWORD}
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - matrix_postgres_data:/var/lib/postgresql/data
    networks:
      homelab:
        ipv4_address: 172.20.0.20
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse -d synapse"]
      interval: 10s
      timeout: 5s
      retries: 5

  matrix-synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    restart: unless-stopped
    env_file: ../.env
    environment:
      SYNAPSE_SERVER_NAME: ${MATRIX_DOMAIN}
      SYNAPSE_REPORT_STATS: "no"
    volumes:
      - ./synapse:/data
    depends_on:
      matrix-postgres:
        condition: service_healthy
    networks:
      homelab:
        ipv4_address: 172.20.0.21

  matrix-cinny:
    image: ghcr.io/cinnyapp/cinny:latest
    container_name: matrix-cinny
    restart: unless-stopped
    volumes:
      - ./cinny/config.json:/app/config.json:ro
    networks:
      homelab:
        ipv4_address: 172.20.0.22
    depends_on:
      - matrix-synapse

  matrix-bot:
    build: ./bot
    container_name: matrix-bot
    restart: unless-stopped
    env_file: ./bot/.env
    volumes:
      - matrix_bot_store:/app/store
    networks:
      homelab:
        ipv4_address: 172.20.0.23
    depends_on:
      - matrix-synapse

volumes:
  matrix_postgres_data:
  matrix_bot_store:

networks:
  homelab:
    external: true
