version: "3.8"

services:
  # PostgreSQL Database
  nextcloud-db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD:-nextcloud_secure_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      homelab:
        ipv4_address: 172.20.0.50

  # Redis Cache
  nextcloud-redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_secure_password}
    volumes:
      - nextcloud_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      homelab:
        ipv4_address: 172.20.0.58

  # Collabora Online - Document Server
  collabora:
    image: collabora/code:latest
    container_name: nextcloud-collabora
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      - aliasgroup1=https://files.acebuddy.quest:443
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - username=${COLLABORA_USERNAME:-admin}
      - password=${COLLABORA_PASSWORD:-collabora_secure_password}
      - dictionaries=en_US
      - DONT_GEN_SSL_CERT=true
    networks:
      homelab:
        ipv4_address: 172.20.0.53

  # Nextcloud Push Daemon for High Performance Backend
  # Note: This service will be started after notify_push app is installed
  # nextcloud-push:
  #   image: nextcloud:stable-fpm
  #   container_name: nextcloud-push
  #   restart: unless-stopped
  #   entrypoint: /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push
  #   command: /var/www/html/config/config.php
  #   environment:
  #     PORT: 7867
  #     NEXTCLOUD_URL: http://nextcloud-web
  #   volumes:
  #     - nextcloud_data:/var/www/html
  #   depends_on:
  #     - nextcloud-web
  #     - nextcloud-redis
  #   networks:
  #     homelab:
  #       ipv4_address: 172.20.0.54

  # Nextcloud App Server
  nextcloud-app:
    image: nextcloud:stable-fpm
    container_name: nextcloud-app
    restart: unless-stopped
    environment:
      # Database
      POSTGRES_HOST: nextcloud-db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD:-nextcloud_secure_password}
      # Redis
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD:-redis_secure_password}
      # Nextcloud
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER:-admin}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD:-admin_secure_password}
      NEXTCLOUD_TRUSTED_DOMAINS: files.acebuddy.quest localhost
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: files.acebuddy.quest
      # Performance & Features
      PHP_MEMORY_LIMIT: 2G
      PHP_UPLOAD_LIMIT: 10G
      DEFAULT_PHONE_REGION: ${DEFAULT_PHONE_REGION:-US}
      # Email
      SMTP_HOST: ${SMTP_HOST:-mail.acebuddy.quest}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURE: ${SMTP_SECURE:-tls}
      SMTP_NAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-nextcloud}
      MAIL_DOMAIN: ${MAIL_DOMAIN:-acebuddy.quest}
    volumes:
      - nextcloud_data:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
    networks:
      homelab:
        ipv4_address: 172.20.0.51

  # Nginx Web Server
  nextcloud-web:
    image: nginx:alpine
    container_name: nextcloud-web
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud_data:/var/www/html:ro
    depends_on:
      - nextcloud-app
    networks:
      homelab:
        ipv4_address: 172.20.0.55

  # Cron Job Container
  nextcloud-cron:
    image: nextcloud:stable-fpm
    container_name: nextcloud-cron
    restart: unless-stopped
    entrypoint: /cron.sh
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - nextcloud-app
      - nextcloud-db
      - nextcloud-redis
    networks:
      homelab:
        ipv4_address: 172.20.0.56

volumes:
  nextcloud_db:
    driver: local
  nextcloud_data:
    driver: local
  nextcloud_redis:
    driver: local

networks:
  homelab:
    external: true
