version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      homelab:
        ipv4_address: 172.20.0.30

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      homelab:
        ipv4_address: 172.20.0.31
    depends_on:
      - ollama

volumes:
  ollama_data:
  open_webui_data:

networks:
  homelab:
    external: true
